name: CI todo-service pipeline

on:
  push:
    branches:
      - feat/*
      - development
      - main

jobs:
  build-test:
    name: ğŸ§ª Build, Migrate, and Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ› Checkout code
        uses: actions/checkout@v4

      - name: ğŸ§° Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: ğŸ“¦ Install dependencies
        run: |
          go mod download
        
      - name: âœ… Run linters
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0
          working-directory: backend

      - name: ğŸ§ª Run tests
        run: |
          go test ./... -v